name: "Release Changelog Version"
description: "Create new version out of an unreleased section in changelog file"
branding:
  icon: "file-text"
  color: "green"
runs:
  using: "docker"
  image: "Dockerfile"
